### PR TITLE
feat: Form validation

### PR DESCRIPTION
**Pull request by monoMonu**
## Description

Fixed form validation bug

### CODE REVIEW

**Review by Sanchitbajaj02 — APPROVED** [review]

**Comment by monoMonu** [comment]
@Sanchitbajaj02 can you check if everything is alright?

**Comment by Sanchitbajaj02** [comment]
> @Sanchitbajaj02 can you please check if everything is alright?

Title needs formatting. You can refer the docs/commitlint.md for the proper pr name

**Comment by monoMonu** [comment]
@Sanchitbajaj02 Can I close this PR and make another for the same issue?

**Comment by Sanchitbajaj02** [comment]
> @Sanchitbajaj02 Can I close this PR and make another for the same issue?

why? just edit the pr description

image

**Comment by monoMonu** [comment]
> > @Sanchitbajaj02 Can I close this PR and make another for the same issue?
> 
> why? just edit the pr description
> 
> image

I have tried many times, but it didn't work

**Pull request merged**
