### PR TITLE
style: add contribute page

### PR DESCRIPTION
**Pull request by Girishbari**
## Related Issue

Reference Issue #82 
## Description

Added contributor page with `/contribute` route

## Screenshots

image

### CODE REVIEW

**Comment by Sanchitbajaj02** [comment]
Hi @Girishbari 

UI is not properly handled for mobile screens. Please do it

image

One more thing, use [tinypng.com](https://tinypng.com/) to compress the size of images that you have added for sample.

**Comment by Sanchitbajaj02** [comment]
image

Give a proper spacing, give atleast `my-4` and make step 3 bold and increase font size

**Comment by Girishbari** [comment]
surre

**Comment by Girishbari** [comment]
will this do for mobile 
image

**Pull request merged**
