### PR TITLE
fix: Created LEARN.md

### LINKED ISSUE #334: Missing LEARN.md_Docs:
### What you want to add in the documentation?

Learn.md file is missing in our current repository 
The learn.md file in GitHub is typically used as a resource to provide guidance, tutorials, or educational content related to a specific repository. This file can serve various purposes, such as introducing new users to the project, providing detailed instructions for using the codebase, or offering learning pathways for different topics covered by the repository.

@Sanchitbajaj02 assign this issue to me I will add it, I am working under gssoc

### Add screenshots

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Meetjain1**
## Related Issue
closes #334 

## Description
created LEARN.md file from scratch.

## Summary by CodeRabbit

- **Documentation**
  - Updated `LEARN.md` file to introduce the Palettegram Website project, tech stack, learning resources, and FAQ section.

### CODE REVIEW

**Comment by Meetjain1** [comment]
@Sanchitbajaj02 have a look on this pr . Thankyou

**Review by Sanchitbajaj02 — APPROVED** [review]
LGTM

**Comment by Meetjain1** [comment]
@Sanchitbajaj02 gssoc label is wrong please change it .
currently "gsssoc" should be "gssoc"

**Comment by Sanchitbajaj02** [comment]
> @Sanchitbajaj02 gssoc label is wrong please change it . currently "gsssoc" should be "gssoc"

Thanks, for informing. It is changed now

**Pull request merged**
