### PR TITLE
feat: Terms page line styling fixed some padding added

### PR DESCRIPTION
**Pull request by RamakrushnaBiswal**
## Related Issue

#352 solved

## Description
Terms page line styling fixed some padding added

## Screenshots

image

## Summary by CodeRabbit

- **Style**
  - Improved the layout and responsiveness of the Terms page by adding new styles to the section element.

### CODE REVIEW

**Comment by yashd-dev** [comment]
@Sanchitbajaj02 could you merge this PR? It looks good to me.

**Comment by Sanchitbajaj02** [comment]
> @Sanchitbajaj02 could you merge this PR? It looks good to me.

This one and all are in the review process. Will merge them by Monday

**Review by Sanchitbajaj02 — APPROVED** [review]
Merging, LGTM

**Comment by RamakrushnaBiswal** [comment]
@yashd-dev @Sanchitbajaj02 please add some labels

**Comment by Sanchitbajaj02** [comment]
> @yashd-dev @Sanchitbajaj02 please add some labels

Since it was only a one line change so I have given you the `gssoc` label which will grant you 1point on leaderboard

**Pull request merged**
