### PR TITLE
feat: rendering the comments and pull requests for #191

### PR DESCRIPTION
**Pull request by Girishbari**
## Related Issue
there was the need to render comments 

## Description
utilized the /post/:postId section to render comments as well as to let user add comments and also taken care of some basic UI 

## Screenshot
image

### CODE REVIEW

**Comment by arya2004** [comment]
looks good to me

**Comment by Girishbari** [comment]
okay then no worries

**Comment by Sanchitbajaj02** [comment]
@Girishbari Please update the pull request to the lates commit and update few things.

- create a seperate component called singleComment which will contain the UI of the comment and we will just iterate over it to show.
- add a comment length of 250 characters in the comment as well. Refer the same from add post box.

**Comment by Girishbari** [comment]
okay, on it

**Review by Sanchitbajaj02 — APPROVED** [review]

**Pull request merged**
