### PR TITLE
chore: merged userprofile's post ui with feed's post ui

### PR DESCRIPTION
**Pull request by Girishbari**
## Related Issue

FIx: #227
## Description

I have successfully merged POST UI which was different earlier, I have used the latest schema (took from @IrfanshaikH-7 ) which I don't think so present in production, however I still omitted to push schema.json,

### CODE REVIEW

**Comment by Girishbari** [comment]
With new schema update profile won't work, once #241 merged properly, I think we can raise this issue

**Comment by Girishbari** [comment]
@Sanchitbajaj02  this PR hasnt been merged, is there any prob with it

**Comment by Sanchitbajaj02** [comment]
> @Sanchitbajaj02 this PR hasnt been merged, is there any prob with it

I'm not getting enough time to fully review this PR. Will merge it by weekend

**Comment by Girishbari** [comment]
oh, okay

**Pull request merged**
