### PR TITLE
fix: improved the blur effect of navbar

### PR DESCRIPTION
**Pull request by Amitooo1**
fixes: #298 

## Description
prior:
image

Now:
image

## Summary by CodeRabbit

- **Style**
	- Updated the navbar's visual styling to include a subtle backdrop blur effect.

### CODE REVIEW

**Comment by Amitooo1** [comment]
@Sanchitbajaj02 can you please review this under GSSOC'24

**Comment by Sanchitbajaj02** [comment]
@Amitooo1 please resolve merge conflicts

**Comment by Sanchitbajaj02** [comment]
@Amitooo1 also explain what your PR do different than #301.

If you can't justify in 24 hrs, I will close this

**Comment by Amitooo1** [comment]
@Sanchitbajaj02  you can see in MR #301 padding is removed
image
while in my MR padding remain intact and as required the blur effect is distributed evenly throughout the navbar
image

**Comment by Amitooo1** [comment]
Which looks more visually appealing and not so compact as in #301

**Pull request merged**
