### PR TITLE
fix: tour popup above cursor

### LINKED ISSUE #376: Bug: Cursor Disappears Inside Tour Popup
### What happened?

When opening the Tour popup on the platform, the cursor disappears entirely when we move it over the popup box. This makes it hard to interact with "next" button within the tour popup box.
The expected behavior would be for the cursor to remain visible within the popup, allowing users to click on buttons and navigate the tour content. The missing cursor creates a frustrating experience as it hinders the intended functionality of the tour.

### Add screenshots

Screenshot 2024-06-13 113907
Screenshot 2024-06-13 113926

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by SuperSahitya**
## Related Issue

closes #376 

## Description

Fixed the bug that causes the tour popup to appear above cursor

## Screenshots

image

## Summary by CodeRabbit

- **New Features**
  - Introduced a custom `z-index` value (900) for enhanced layering control.

- **Style**
  - Updated `.shepherd-element` with `z-custom` property.
  - Added `.shepherd-modal-overlay-container` class with `z-50`.

### CODE REVIEW

**Comment by Amitooo1** [comment]
Good work @SuperSahitya 👏

**Comment by SuperSahitya** [comment]
@Sanchitbajaj02  Should I work on other issues, or do I need to be assigned the issues before creating a PR ?

**Comment by Sanchitbajaj02** [comment]
> @Sanchitbajaj02 Should I work on other issues, or do I need to be assigned the issues before creating a PR ?

you can take up other issues. Due to some personal issues, I am having trouble focusing on the project. I assure you that it gets merged soon

**Review by Sanchitbajaj02 — APPROVED** [review]
LGTM

**Pull request merged**
