### PR TITLE
the registration form has been validated.

### PR DESCRIPTION
**Pull request by Sanjana787**
## Related Issue

# 197 form validation

## Description

the user form is validated to accept only character values within the length of 2 to 25.

### CODE REVIEW

**Comment by Girishbari** [comment]
hi @Sanjana787 check you comment title add **feat: ...** if you added something new or  add **refactor : ...** because untill then your PR title checker  will not let your pr to pass

also do add the issue number using **ex #..** in the description

**Review by Manishak798 — APPROVED** [review]
This code seems to be correct, wait for the admin to review it for once.

**Comment by Sanchitbajaj02** [comment]
@Sanjana787 few things to work on:

1. Your PR title does not matches with the guidelines of the project. Please fix that.
2. Mention issue properly
3. You regex check does not passing the below test case, so please look into that

image

You can use [regexr](https://regexr.com/) to validate your regex.

**Comment by Manishak798** [comment]
@Sanjana787 have you resolved the issues?

**Review by Manishak798 — CHANGES_REQUESTED** [review]
Any updates on your work?

**Comment by Sanchitbajaj02** [comment]
@Sanjana787 since I don't get any response, I am assigning the issue to you as well as closing this PR

**Pull request closed without merging**
